name: 'Communicate on pull request merged'
description: ''
inputs:
  github-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  comment:
    description: 'A comment to post on a pull request when code changes are merged'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
